### PR TITLE
tool: trivial fix in sel4.py - SMC cap number

### PR DESCRIPTION
**Pull request by malus-brandywine**
The number of "SMC calls" capability in the root CNode is 15 (now).

### CODE REVIEW

**Comment by malus-brandywine** [comment]
Thank you for merging my patches (#7, #9) !   Just this tiny thing was lost while the merge - SMC cap number.

PR#9 was closed for me by github while repositories sync, so I my changes to documentation are lost now. I'm going to resubmit them in new draft RP with new project name used.

PS: By  the way, why MICROKIT_MAX_CHANNELS is 63, not 64? I presume it's just a typo.

**Comment by Ivan-Velickovic** [comment]
> PS: By the way, why MICROKIT_MAX_CHANNELS is 63, not 64? I guess it's just a typo.

It should actually be 62, hopefully the commit message here https://github.com/Ivan-Velickovic/microkit/commit/c53650a0aa85c017314bdb945edf19c3639e48c2 explains the reasoning behind the limit, let me know if it doesn't make sense.

**Comment by malus-brandywine** [comment]
Right! I found the code, where the bits are used, thank you. :)

**Comment by Ivan-Velickovic** [comment]
I'm going to cherry-pick c494f8d124fd4762f09f5c6efe6eda38b38ad06a and apply that. Thanks for the fix.

**Pull request closed without merging**
